-- run this in your Supabase SQL Editor

-- Users Table
CREATE TABLE public.users (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  username text UNIQUE NOT NULL,
  avatar_url text,
  email text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Communities Table
CREATE TABLE public.communities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid REFERENCES public.users(id) NOT NULL,
  name text UNIQUE NOT NULL,
  description text,
  image_url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Community Members
CREATE TABLE public.community_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id bigint REFERENCES public.communities(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  role text DEFAULT 'member',
  joined_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(community_id, user_id)
);

-- Posts Table
CREATE TABLE public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id bigint REFERENCES public.communities(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  content text,
  media jsonb DEFAULT '[]'::jsonb,
  votes_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comments Table
CREATE TABLE public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  parent_comment_id bigint REFERENCES public.comments(id) ON DELETE CASCADE,
  content text NOT NULL,
  votes_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Votes Table
CREATE TABLE public.votes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE,
  comment_id bigint REFERENCES public.comments(id) ON DELETE CASCADE,
  vote_type integer CHECK (vote_type IN (-1, 1)), -- 1 for upvote, -1 for downvote
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, post_id, comment_id) -- User can vote only once per post or comment
);

-- Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;

-- Allow read access for public
CREATE POLICY "Public profiles are viewable by everyone." ON public.users FOR SELECT USING (true);
CREATE POLICY "Communities are viewable by everyone" ON public.communities FOR SELECT USING (true);
CREATE POLICY "Posts are viewable by everyone" ON public.posts FOR SELECT USING (true);
CREATE POLICY "Comments are viewable by everyone" ON public.comments FOR SELECT USING (true);
CREATE POLICY "Community members are viewable by everyone" ON public.community_members FOR SELECT USING (true);
CREATE POLICY "Votes are viewable by everyone" ON public.votes FOR SELECT USING (true);

-- Allow authenticated users to Insert (if they own the token)
-- Insert/Update on users is handled partially by backend bypassing RLS due to anon key usage,
-- BUT if using supabase anon key from backend, it runs with that role. 
-- Best to allow auth users to insert/update their own records
CREATE POLICY "Users can insert their own profile." ON public.users FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.users FOR UPDATE USING (auth.uid() = id);

-- Allow authenticated users to create and manage communities
CREATE POLICY "Authenticated users can create communities" ON public.communities FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Owners can update their communities" ON public.communities FOR UPDATE USING (auth.uid() = owner_id);
CREATE POLICY "Owners can delete their communities" ON public.communities FOR DELETE USING (auth.uid() = owner_id);

-- For communities/posts/comments
CREATE POLICY "Authenticated users can create communities" ON public.communities FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Authenticated users can create posts" ON public.posts FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Authors can update their posts" ON public.posts FOR UPDATE USING (auth.uid() = author_id);
CREATE POLICY "Authors can delete their posts" ON public.posts FOR DELETE USING (auth.uid() = author_id);

CREATE POLICY "Authenticated users can create comments" ON public.comments FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Authors can update their comments" ON public.comments FOR UPDATE USING (auth.uid() = author_id);
CREATE POLICY "Authors can delete their comments" ON public.comments FOR DELETE USING (auth.uid() = author_id);

CREATE POLICY "Authenticated users can join communities" ON public.community_members FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can leave communities" ON public.community_members FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can vote" ON public.votes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Authenticated users can update their vote" ON public.votes FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Authenticated users can remove their vote" ON public.votes FOR DELETE USING (auth.uid() = user_id);

-- Bookmarks Table
CREATE TABLE public.bookmarks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, post_id)
);

ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their bookmarks" ON public.bookmarks FOR ALL USING (auth.uid() = user_id);

-- Storage bucket for post attachments (images/videos/documents)
INSERT INTO storage.buckets (id, name, public)
VALUES ('post-media', 'post-media', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public can view post media"
ON storage.objects FOR SELECT
USING (bucket_id = 'post-media');

CREATE POLICY "Authenticated users can upload post media"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'post-media' AND auth.role() = 'authenticated');

-- Connect (followers/following)
CREATE TABLE IF NOT EXISTS public.follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  following_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (follower_id, following_id),
  CHECK (follower_id <> following_id)
);

ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Follows are viewable by everyone" ON public.follows;
DROP POLICY IF EXISTS "Users can create follows for themselves" ON public.follows;
DROP POLICY IF EXISTS "Users can delete their follows" ON public.follows;

CREATE POLICY "Follows are viewable by everyone"
ON public.follows FOR SELECT USING (true);

CREATE POLICY "Users can create follows for themselves"
ON public.follows FOR INSERT WITH CHECK (auth.uid() = follower_id);

CREATE POLICY "Users can delete their follows"
ON public.follows FOR DELETE USING (auth.uid() = follower_id);

-- Direct chat
CREATE TABLE IF NOT EXISTS public.conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text DEFAULT 'direct' NOT NULL CHECK (type IN ('direct')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.conversation_participants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (conversation_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
  sender_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_created_at
  ON public.messages (conversation_id, created_at DESC);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_conversation_participant(cid bigint, uid uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.conversation_participants cp
    WHERE cp.conversation_id = cid
      AND cp.user_id = uid
  );
$$;

DROP POLICY IF EXISTS "Participants can read conversations" ON public.conversations;
DROP POLICY IF EXISTS "Participants can create conversations" ON public.conversations;
DROP POLICY IF EXISTS "Authenticated users can create conversations" ON public.conversations;
DROP POLICY IF EXISTS "Participants can update conversations" ON public.conversations;
DROP POLICY IF EXISTS "Participants can read participants" ON public.conversation_participants;
DROP POLICY IF EXISTS "Users can insert self participant rows" ON public.conversation_participants;
DROP POLICY IF EXISTS "Participants can read messages" ON public.messages;
DROP POLICY IF EXISTS "Participants can send messages" ON public.messages;

CREATE POLICY "Participants can read conversations"
ON public.conversations FOR SELECT
USING (
  public.is_conversation_participant(conversations.id, auth.uid())
);

CREATE POLICY "Participants can create conversations"
ON public.conversations FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Participants can update conversations"
ON public.conversations FOR UPDATE
USING (
  public.is_conversation_participant(conversations.id, auth.uid())
);

CREATE POLICY "Participants can read participants"
ON public.conversation_participants FOR SELECT
USING (
  public.is_conversation_participant(conversation_participants.conversation_id, auth.uid())
);

CREATE POLICY "Users can insert self participant rows"
ON public.conversation_participants FOR INSERT
WITH CHECK (
  auth.uid() = user_id
  OR public.is_conversation_participant(conversation_participants.conversation_id, auth.uid())
);

CREATE POLICY "Participants can read messages"
ON public.messages FOR SELECT
USING (
  public.is_conversation_participant(messages.conversation_id, auth.uid())
);

CREATE POLICY "Participants can send messages"
ON public.messages FOR INSERT
WITH CHECK (
  auth.uid() = sender_id
  AND public.is_conversation_participant(messages.conversation_id, auth.uid())
);

-- Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  actor_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  type text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_created_at
  ON public.notifications (recipient_id, created_at DESC);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can insert actor notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can update own notifications" ON public.notifications;

CREATE POLICY "Users can read own notifications"
ON public.notifications FOR SELECT
USING (auth.uid() = recipient_id);

CREATE POLICY "Users can insert actor notifications"
ON public.notifications FOR INSERT
WITH CHECK (auth.uid() = actor_id);

CREATE POLICY "Users can update own notifications"
ON public.notifications FOR UPDATE
USING (auth.uid() = recipient_id);

-- User privacy
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_private boolean DEFAULT false NOT NULL;

-- Follow requests for private accounts
CREATE TABLE IF NOT EXISTS public.follow_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  target_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  responded_at timestamp with time zone,
  UNIQUE (requester_id, target_id)
);

ALTER TABLE public.follow_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can create follow requests" ON public.follow_requests;
DROP POLICY IF EXISTS "Users can read own follow requests" ON public.follow_requests;
DROP POLICY IF EXISTS "Targets can update follow requests" ON public.follow_requests;

CREATE POLICY "Users can create follow requests"
ON public.follow_requests FOR INSERT
WITH CHECK (auth.uid() = requester_id);

CREATE POLICY "Users can read own follow requests"
ON public.follow_requests FOR SELECT
USING (auth.uid() = requester_id OR auth.uid() = target_id);

CREATE POLICY "Targets can update follow requests"
ON public.follow_requests FOR UPDATE
USING (auth.uid() = target_id);

-- Message read receipts
CREATE TABLE IF NOT EXISTS public.message_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint REFERENCES public.messages(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (message_id, user_id)
);

ALTER TABLE public.message_receipts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Participants can read receipts" ON public.message_receipts;
DROP POLICY IF EXISTS "Users can upsert own receipts" ON public.message_receipts;

CREATE POLICY "Participants can read receipts"
ON public.message_receipts FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.messages m
    JOIN public.conversation_participants cp ON cp.conversation_id = m.conversation_id
    WHERE m.id = message_receipts.message_id
      AND cp.user_id = auth.uid()
  )
);

CREATE POLICY "Users can upsert own receipts"
ON public.message_receipts FOR INSERT
WITH CHECK (
  auth.uid() = user_id
  AND EXISTS (
    SELECT 1
    FROM public.messages m
    JOIN public.conversation_participants cp ON cp.conversation_id = m.conversation_id
    WHERE m.id = message_receipts.message_id
      AND cp.user_id = auth.uid()
  )
);

CREATE POLICY "Users can update own receipts"
ON public.message_receipts FOR UPDATE
USING (auth.uid() = user_id);

-- Typing status in chat
CREATE TABLE IF NOT EXISTS public.chat_typing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  is_typing boolean DEFAULT false NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  expires_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (conversation_id, user_id)
);

ALTER TABLE public.chat_typing ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Participants can read typing" ON public.chat_typing;
DROP POLICY IF EXISTS "Participants can write typing" ON public.chat_typing;

CREATE POLICY "Participants can read typing"
ON public.chat_typing FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.conversation_participants cp
    WHERE cp.conversation_id = chat_typing.conversation_id
      AND cp.user_id = auth.uid()
  )
);

CREATE POLICY "Participants can write typing"
ON public.chat_typing FOR INSERT
WITH CHECK (
  auth.uid() = user_id
  AND EXISTS (
    SELECT 1
    FROM public.conversation_participants cp
    WHERE cp.conversation_id = chat_typing.conversation_id
      AND cp.user_id = auth.uid()
  )
);

CREATE POLICY "Participants can update own typing"
ON public.chat_typing FOR UPDATE
USING (auth.uid() = user_id);

-- Moderation block and report
CREATE TABLE IF NOT EXISTS public.user_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocker_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  blocked_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (blocker_id, blocked_id),
  CHECK (blocker_id <> blocked_id)
);

ALTER TABLE public.user_blocks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own blocks" ON public.user_blocks;
CREATE POLICY "Users can manage own blocks"
ON public.user_blocks FOR ALL
USING (auth.uid() = blocker_id)
WITH CHECK (auth.uid() = blocker_id);

CREATE TABLE IF NOT EXISTS public.reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  target_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  post_id bigint REFERENCES public.posts(id) ON DELETE SET NULL,
  comment_id bigint REFERENCES public.comments(id) ON DELETE SET NULL,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE SET NULL,
  reason text NOT NULL,
  details text,
  status text NOT NULL DEFAULT 'open',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can create own reports" ON public.reports;
DROP POLICY IF EXISTS "Users can read own reports" ON public.reports;
CREATE POLICY "Users can create own reports"
ON public.reports FOR INSERT
WITH CHECK (auth.uid() = reporter_id);

CREATE POLICY "Users can read own reports"
ON public.reports FOR SELECT
USING (auth.uid() = reporter_id);

-- Notification preferences
CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id uuid PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  follows_enabled boolean DEFAULT true NOT NULL,
  follow_requests_enabled boolean DEFAULT true NOT NULL,
  messages_enabled boolean DEFAULT true NOT NULL,
  comments_enabled boolean DEFAULT true NOT NULL,
  mentions_enabled boolean DEFAULT true NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own notification preferences" ON public.notification_preferences;
CREATE POLICY "Users can manage own notification preferences"
ON public.notification_preferences FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
