-- Run this in the SAME Supabase project used by your deployed backend.
-- Safe to rerun: all statements are idempotent or guarded.

-- 1) Core social columns
ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS is_private boolean DEFAULT false NOT NULL;

-- 2) Follows
CREATE TABLE IF NOT EXISTS public.follows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  following_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (follower_id, following_id),
  CHECK (follower_id <> following_id)
);

ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Follows are viewable by everyone" ON public.follows;
DROP POLICY IF EXISTS "Users can create follows for themselves" ON public.follows;
DROP POLICY IF EXISTS "Users can delete their follows" ON public.follows;
CREATE POLICY "Follows are viewable by everyone"
ON public.follows FOR SELECT USING (true);
CREATE POLICY "Users can create follows for themselves"
ON public.follows FOR INSERT WITH CHECK (auth.uid() = follower_id);
CREATE POLICY "Users can delete their follows"
ON public.follows FOR DELETE USING (auth.uid() = follower_id);

-- 3) Private-account follow requests
CREATE TABLE IF NOT EXISTS public.follow_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  target_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  responded_at timestamp with time zone,
  UNIQUE (requester_id, target_id)
);

ALTER TABLE public.follow_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can create follow requests" ON public.follow_requests;
DROP POLICY IF EXISTS "Users can read own follow requests" ON public.follow_requests;
DROP POLICY IF EXISTS "Targets can update follow requests" ON public.follow_requests;
CREATE POLICY "Users can create follow requests"
ON public.follow_requests FOR INSERT
WITH CHECK (auth.uid() = requester_id);
CREATE POLICY "Users can read own follow requests"
ON public.follow_requests FOR SELECT
USING (auth.uid() = requester_id OR auth.uid() = target_id);
CREATE POLICY "Targets can update follow requests"
ON public.follow_requests FOR UPDATE
USING (auth.uid() = target_id);

-- 4) Direct chat
CREATE TABLE IF NOT EXISTS public.conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text DEFAULT 'direct' NOT NULL CHECK (type IN ('direct')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.conversation_participants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (conversation_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
  sender_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_created_at
  ON public.messages (conversation_id, created_at DESC);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_conversation_participant(cid bigint, uid uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.conversation_participants cp
    WHERE cp.conversation_id = cid
      AND cp.user_id = uid
  );
$$;

DROP POLICY IF EXISTS "Participants can read conversations" ON public.conversations;
DROP POLICY IF EXISTS "Participants can create conversations" ON public.conversations;
DROP POLICY IF EXISTS "Participants can update conversations" ON public.conversations;
DROP POLICY IF EXISTS "Participants can read participants" ON public.conversation_participants;
DROP POLICY IF EXISTS "Users can insert self participant rows" ON public.conversation_participants;
DROP POLICY IF EXISTS "Participants can read messages" ON public.messages;
DROP POLICY IF EXISTS "Participants can send messages" ON public.messages;

CREATE POLICY "Participants can read conversations"
ON public.conversations FOR SELECT
USING (
  public.is_conversation_participant(conversations.id, auth.uid())
);

CREATE POLICY "Participants can create conversations"
ON public.conversations FOR INSERT
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Participants can update conversations"
ON public.conversations FOR UPDATE
USING (
  public.is_conversation_participant(conversations.id, auth.uid())
);

CREATE POLICY "Participants can read participants"
ON public.conversation_participants FOR SELECT
USING (
  public.is_conversation_participant(conversation_participants.conversation_id, auth.uid())
);

CREATE POLICY "Users can insert self participant rows"
ON public.conversation_participants FOR INSERT
WITH CHECK (
  auth.uid() = user_id
  OR public.is_conversation_participant(conversation_participants.conversation_id, auth.uid())
);

CREATE POLICY "Participants can read messages"
ON public.messages FOR SELECT
USING (
  public.is_conversation_participant(messages.conversation_id, auth.uid())
);

CREATE POLICY "Participants can send messages"
ON public.messages FOR INSERT
WITH CHECK (
  auth.uid() = sender_id
  AND public.is_conversation_participant(messages.conversation_id, auth.uid())
);

-- 5) Notifications + preferences
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  actor_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  type text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_created_at
  ON public.notifications (recipient_id, created_at DESC);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can insert actor notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can update own notifications" ON public.notifications;
CREATE POLICY "Users can read own notifications"
ON public.notifications FOR SELECT
USING (auth.uid() = recipient_id);
CREATE POLICY "Users can insert actor notifications"
ON public.notifications FOR INSERT
WITH CHECK (auth.uid() = actor_id);
CREATE POLICY "Users can update own notifications"
ON public.notifications FOR UPDATE
USING (auth.uid() = recipient_id);

CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id uuid PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  follows_enabled boolean DEFAULT true NOT NULL,
  follow_requests_enabled boolean DEFAULT true NOT NULL,
  messages_enabled boolean DEFAULT true NOT NULL,
  comments_enabled boolean DEFAULT true NOT NULL,
  mentions_enabled boolean DEFAULT true NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own notification preferences" ON public.notification_preferences;
CREATE POLICY "Users can manage own notification preferences"
ON public.notification_preferences FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 6) Moderation + chat quality-of-life
CREATE TABLE IF NOT EXISTS public.user_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocker_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  blocked_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (blocker_id, blocked_id),
  CHECK (blocker_id <> blocked_id)
);

ALTER TABLE public.user_blocks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own blocks" ON public.user_blocks;
CREATE POLICY "Users can manage own blocks"
ON public.user_blocks FOR ALL
USING (auth.uid() = blocker_id)
WITH CHECK (auth.uid() = blocker_id);

CREATE TABLE IF NOT EXISTS public.reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  target_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  post_id bigint REFERENCES public.posts(id) ON DELETE SET NULL,
  comment_id bigint REFERENCES public.comments(id) ON DELETE SET NULL,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE SET NULL,
  reason text NOT NULL,
  details text,
  status text NOT NULL DEFAULT 'open',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can create own reports" ON public.reports;
DROP POLICY IF EXISTS "Users can read own reports" ON public.reports;
CREATE POLICY "Users can create own reports"
ON public.reports FOR INSERT
WITH CHECK (auth.uid() = reporter_id);
CREATE POLICY "Users can read own reports"
ON public.reports FOR SELECT
USING (auth.uid() = reporter_id);

CREATE TABLE IF NOT EXISTS public.message_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint REFERENCES public.messages(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (message_id, user_id)
);

ALTER TABLE public.message_receipts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Participants can read receipts" ON public.message_receipts;
DROP POLICY IF EXISTS "Users can upsert own receipts" ON public.message_receipts;
DROP POLICY IF EXISTS "Users can update own receipts" ON public.message_receipts;

CREATE POLICY "Participants can read receipts"
ON public.message_receipts FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.messages m
    JOIN public.conversation_participants cp ON cp.conversation_id = m.conversation_id
    WHERE m.id = message_receipts.message_id
      AND cp.user_id = auth.uid()
  )
);

CREATE POLICY "Users can upsert own receipts"
ON public.message_receipts FOR INSERT
WITH CHECK (
  auth.uid() = user_id
  AND EXISTS (
    SELECT 1
    FROM public.messages m
    JOIN public.conversation_participants cp ON cp.conversation_id = m.conversation_id
    WHERE m.id = message_receipts.message_id
      AND cp.user_id = auth.uid()
  )
);

CREATE POLICY "Users can update own receipts"
ON public.message_receipts FOR UPDATE
USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.chat_typing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  is_typing boolean DEFAULT false NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  expires_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (conversation_id, user_id)
);

ALTER TABLE public.chat_typing ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Participants can read typing" ON public.chat_typing;
DROP POLICY IF EXISTS "Participants can write typing" ON public.chat_typing;
DROP POLICY IF EXISTS "Participants can update own typing" ON public.chat_typing;

CREATE POLICY "Participants can read typing"
ON public.chat_typing FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.conversation_participants cp
    WHERE cp.conversation_id = chat_typing.conversation_id
      AND cp.user_id = auth.uid()
  )
);

CREATE POLICY "Participants can write typing"
ON public.chat_typing FOR INSERT
WITH CHECK (
  auth.uid() = user_id
  AND EXISTS (
    SELECT 1
    FROM public.conversation_participants cp
    WHERE cp.conversation_id = chat_typing.conversation_id
      AND cp.user_id = auth.uid()
  )
);

CREATE POLICY "Participants can update own typing"
ON public.chat_typing FOR UPDATE
USING (auth.uid() = user_id);

-- 7) Quick verification query (run after migration)
-- SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename IN (
--   'follows','follow_requests','conversations','conversation_participants','messages',
--   'notifications','notification_preferences','user_blocks','reports','message_receipts','chat_typing'
-- ) ORDER BY tablename;
